logpath = "log/"
debug = true

[utopia]
debug = true               #если истина то запускать имитатор 
device = "rtu:///dev/com2"
baudrate = 38400

[modbus]
# device="rtu:///dev/ttyUSB0"
# device = "rtu:///dev/ttyEXTRA2_00"
device = "rtu:///dev/com1"
baudrate = 19200
parity = "N"
uid = 247

[trafficdata]
work = false
debug = true       #Запускать иммитатор
host = "127.0.0.1"
port = 1666
listen = 1667
chanels = 16
diaps = 1
diap = 0

[modbusradar]
radar = true  #если истинно нужно открывать прием сигналов радара
master = true
debug = true
# host = "178.176.55.215"
host = "127.0.0.1"
port = 15001
id = 11
chanels = 16
diaps = 1
diap = 0
