logpath = "log/"
id = 104
[utopia]
debug = false #если истина то запускать имитатор 
# device = "rtu:///dev/com0"
device = "/dev/com0"
baudrate = 38400
lostControl = 5      #Время потеря контроля Utopia
recode = true
tmin = 5             #Минимальное время фазы
replay = true        #Если истина то отвечаем Утоппи если нет связи с КДМ   

[modbus]
# device="rtu:///dev/ttyUSB0"
# device = "rtu:///dev/ttyEXTRA2_00"
device = "rtu:///dev/com1"
baudrate = 19200
parity = "N"
uid = 1
debug = false
log = false

[trafficdata]
work = false
debug = false      #Запускать иммитатор
host = "127.0.0.1"
port = 1666
listen = 1667
chanels = 16
diaps = 1
diap = 0

[modbusradar]
radar = true            #если истинно нужно открывать прием сигналов радара
master = true
debug = false
host = "10.135.123.150"
# host = "127.0.0.1"
port = 15000
id = 11
chanels = 8
diaps = 1
diap = 0
