logpath = "log/"
[utopia]
work = true
debug = true               #если истина то запускать имитатор 
device = "rtu:///dev/com1"
baudrate = 19200
parity = "N"
uid = 247
[trafficdata]
work = true
debug = true       #Запускать иммитатор
host = "127.0.0.1"
port = 1666
listen = 1667
chanels = 16
